# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='email',
            field=models.EmailField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='info',
            field=models.TextField(max_length=200),
        ),
    ]
